server:
  port: 8861
spring:
  application:
    name: order-sentinel
  cloud:
    sentinel:
      transport:
        dashboard: 10.100.103.124:8858
      web-context-unify: false # 默认将调用链路收敛，导致链路流控效果无效