server:
  port: 8019
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 10.100.103.124:8847
      application: seata-server
      username: nacos
      password: nacos
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: 10.100.103.124:8847
      username: nacos
      password: nacos
      group: SEATA_GROUP

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.100.103.124:3306/seata_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: P@ssw0rd!
  application:
    name: alibaba-order-seata
  cloud:
    nacos:
      server-addr: 10.100.103.124:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public
    alibaba:
      seata:
        tx-service-group: guangzhou
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.tulingxueyuan.order.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.tulingxueyuan.order.feign: debug
  config: classpath:logback-spring.xml
